/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_github_yanbober_ndkapplication_NdkJniUtils */

#ifndef _Included_cn_zero_shadowkcp_NativeHelper
#define _Included_cn_zero_shadowkcp_NativeHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_github_yanbober_ndkapplication_NdkJniUtils
 * Method:    getCLanguageString
 * Signature: ()Ljava/lang/String;
 */
//JNIEXPORT jstring JNICALL Java_cn_zero_shadowkcp_NativeHelper_getCLanguageString
//  (JNIEnv *, jobject);
JNIEXPORT jstring JNICALL Java_cn_zero_shadowkcp_NativeHelper_startServer
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif